In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("employee_data.csv")
df

   Employee id     Name   Age  Salary          City  Bonus  Total Compensation
0            1    Sahil  25.0   55000      New York   5500               60500
1            2     john   NaN   60000   Los Angeles   6000               66000
2            3      NaN  35.0   70000       Chicago   7000               77000
3            4    susan  40.0   80000       Houston   8000               88000
4            5     lisa  45.0   90000           NaN   9000               99000
5            6    david  50.0  100000  Philadelphia  10000              110000
6            7  jessica  55.0  110000   San Antonio  11000              121000
7            8   robert   NaN  120000     San Diego  12000              132000
8            9    linda  65.0  130000        Dallas  13000              143000
9           10    james  70.0  140000      San Jose  14000              154000

In [4]:
df.isnull().sum()

Employee id           0
Name                  1
Age                   2
Salary                0
City                  1
Bonus                 0
Total Compensation    0
dtype: int64

In [5]:
# if we have some thing not neccesary data we can drop it with using dropna() method
# df.dropna(aixs=0, inplace=True) # axis=0 means drop rows with missing values
# df.dropna(axis=1, inplace=True) # axis=1 means drop columns with missing values
# df.dropna(inplace=True) # default is axis=0

# also we have fillna() method to fill missing values with some specific value
# df.fillna(0, inplace=True) # fill missing values with 0

In [6]:
df["Age"].fillna(df["Age"].mean(), inplace=True)
df

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_12328\3445616279.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
0,1,Sahil,25.000,55000,New York,5500,60500
1,2,john,48.125,60000,Los Angeles,6000,66000
2,3,NaN,35.000,70000,Chicago,7000,77000
3,4,susan,40.000,80000,Houston,8000,88000
4,5,lisa,45.000,90000,NaN,9000,99000
5,6,david,50.000,100000,Philadelphia,10000,110000
6,7,jessica,55.000,110000,San Antonio,11000,121000
7,8,robert,48.125,120000,San Diego,12000,132000
8,9,linda,65.000,130000,Dallas,13000,143000
9,10,james,70.000,140000,San Jose,14000,154000

In [7]:
df["Name"] = df["Name"].fillna("Unknown")
df

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
0,1,Sahil,25.000,55000,New York,5500,60500
1,2,john,48.125,60000,Los Angeles,6000,66000
2,3,Unknown,35.000,70000,Chicago,7000,77000
3,4,susan,40.000,80000,Houston,8000,88000
4,5,lisa,45.000,90000,NaN,9000,99000
5,6,david,50.000,100000,Philadelphia,10000,110000
6,7,jessica,55.000,110000,San Antonio,11000,121000
7,8,robert,48.125,120000,San Diego,12000,132000
8,9,linda,65.000,130000,Dallas,13000,143000
9,10,james,70.000,140000,San Jose,14000,154000

In [8]:
df["City"] = df["City"].fillna(df["City"].mode()[0])
df

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
0,1,Sahil,25.000,55000,New York,5500,60500
1,2,john,48.125,60000,Los Angeles,6000,66000
2,3,Unknown,35.000,70000,Chicago,7000,77000
3,4,susan,40.000,80000,Houston,8000,88000
4,5,lisa,45.000,90000,Chicago,9000,99000
5,6,david,50.000,100000,Philadelphia,10000,110000
6,7,jessica,55.000,110000,San Antonio,11000,121000
7,8,robert,48.125,120000,San Diego,12000,132000
8,9,linda,65.000,130000,Dallas,13000,143000
9,10,james,70.000,140000,San Jose,14000,154000

In [10]:
# sorting data 
# df.sort_values(by = "column_name", ascending=True/False, inplace=True)

df.sort_values(by="Age", ascending=False, inplace=True)
df

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
9,10,james,70.000,140000,San Jose,14000,154000
8,9,linda,65.000,130000,Dallas,13000,143000
6,7,jessica,55.000,110000,San Antonio,11000,121000
5,6,david,50.000,100000,Philadelphia,10000,110000
1,2,john,48.125,60000,Los Angeles,6000,66000
7,8,robert,48.125,120000,San Diego,12000,132000
4,5,lisa,45.000,90000,Chicago,9000,99000
3,4,susan,40.000,80000,Houston,8000,88000
2,3,Unknown,35.000,70000,Chicago,7000,77000
0,1,Sahil,25.000,55000,New York,5500,60500

In [15]:
df.sort_values(by=["Age", "Salary"], ascending=[False, False], inplace=True)
df

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
9,10,james,70.000,140000,San Jose,14000,154000
8,9,linda,65.000,130000,Dallas,13000,143000
6,7,jessica,55.000,110000,San Antonio,11000,121000
5,6,david,50.000,100000,Philadelphia,10000,110000
7,8,robert,48.125,120000,San Diego,12000,132000
1,2,john,48.125,60000,Los Angeles,6000,66000
4,5,lisa,45.000,90000,Chicago,9000,99000
3,4,susan,40.000,80000,Houston,8000,88000
2,3,Unknown,35.000,70000,Chicago,7000,77000
0,1,Sahil,25.000,55000,New York,5500,60500

In [20]:
df["Age"] = df["Age"].astype(int)
df

   Employee id     Name  Age  Salary          City  Bonus  Total Compensation
9           10    james   70  140000      San Jose  14000              154000
8            9    linda   65  130000        Dallas  13000              143000
6            7  jessica   55  110000   San Antonio  11000              121000
5            6    david   50  100000  Philadelphia  10000              110000
7            8   robert   48  120000     San Diego  12000              132000
1            2     john   48   60000   Los Angeles   6000               66000
4            5     lisa   45   90000       Chicago   9000               99000
3            4    susan   40   80000       Houston   8000               88000
2            3  Unknown   35   70000       Chicago   7000               77000
0            1    Sahil   25   55000      New York   5500               60500

In [22]:
grouped = df.groupby("Age")["Salary"].sum()
grouped

Age
25     55000
35     70000
40     80000
45     90000
48    180000
50    100000
55    110000
65    130000
70    140000
Name: Salary, dtype: int64

In [23]:
# multy grouping
grouped = df.groupby(["Age","Name"])["Salary"].sum()
grouped

Age  Name
25   Sahil       55000
35   Unknown     70000
40   susan       80000
45   lisa        90000
48   john        60000
     robert     120000
50   david      100000
55   jessica    110000
65   linda      130000
70   james      140000
Name: Salary, dtype: int64