In [16]:
import pandas as pd

In [17]:
#read data from csv file into dataframe
df = pd.read_csv("sales_data_sample.csv", encoding='latin1')

In [18]:
# df.isnull().sum()
# df.info()
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [19]:
df.shape

(2823, 25)

In [20]:
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

In [21]:
# sales_column = df[df['SALES'] > 3553.889072]
# sales_column

# ordernumber_sales = df[['ORDERNUMBER', 'SALES']]
# ordernumber_sales

In [22]:
data = {
    "Name" : ['Sahil', 'john', 'michael', 'susan', 'lisa', 'david', 'jessica', 'robert', 'linda', 'james'],
    "Age" : [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
    "Salary" : [50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 130000, 140000],
    "City" : ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose']
}

df1 = pd.DataFrame(data)
df1

      Name  Age  Salary          City
0    Sahil   25   50000      New York
1     john   30   60000   Los Angeles
2  michael   35   70000       Chicago
3    susan   40   80000       Houston
4     lisa   45   90000       Phoenix
5    david   50  100000  Philadelphia
6  jessica   55  110000   San Antonio
7   robert   60  120000     San Diego
8    linda   65  130000        Dallas
9    james   70  140000      San Jose

In [23]:
#using square bracket to add new column
df1["Bonus"] = df1["Salary"] * 0.1
df1

      Name  Age  Salary          City    Bonus
0    Sahil   25   50000      New York   5000.0
1     john   30   60000   Los Angeles   6000.0
2  michael   35   70000       Chicago   7000.0
3    susan   40   80000       Houston   8000.0
4     lisa   45   90000       Phoenix   9000.0
5    david   50  100000  Philadelphia  10000.0
6  jessica   55  110000   San Antonio  11000.0
7   robert   60  120000     San Diego  12000.0
8    linda   65  130000        Dallas  13000.0
9    james   70  140000      San Jose  14000.0

In [24]:
#using insert method to add new column
df1.insert(5, "Total Compensation", df1["Salary"] + df1["Bonus"])
df1

      Name  Age  Salary          City    Bonus  Total Compensation
0    Sahil   25   50000      New York   5000.0             55000.0
1     john   30   60000   Los Angeles   6000.0             66000.0
2  michael   35   70000       Chicago   7000.0             77000.0
3    susan   40   80000       Houston   8000.0             88000.0
4     lisa   45   90000       Phoenix   9000.0             99000.0
5    david   50  100000  Philadelphia  10000.0            110000.0
6  jessica   55  110000   San Antonio  11000.0            121000.0
7   robert   60  120000     San Diego  12000.0            132000.0
8    linda   65  130000        Dallas  13000.0            143000.0
9    james   70  140000      San Jose  14000.0            154000.0

In [25]:
df1
df1.insert(0, "Employee id", range(1, len(df1) + 1))

In [26]:
# .loc[] method to access specific rows and columns
# df.loc[row_indexer, "column_name"] = new_value
df1.loc[0, "Salary"] = 55000
df1

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
0,1,Sahil,25,55000,New York,5000.0,55000.0
1,2,john,30,60000,Los Angeles,6000.0,66000.0
2,3,michael,35,70000,Chicago,7000.0,77000.0
3,4,susan,40,80000,Houston,8000.0,88000.0
4,5,lisa,45,90000,Phoenix,9000.0,99000.0
5,6,david,50,100000,Philadelphia,10000.0,110000.0
6,7,jessica,55,110000,San Antonio,11000.0,121000.0
7,8,robert,60,120000,San Diego,12000.0,132000.0
8,9,linda,65,130000,Dallas,13000.0,143000.0
9,10,james,70,140000,San Jose,14000.0,154000.0

In [27]:
df1.loc[0, "Salary"] = 55000
df1.loc[0, "Bonus"] = df1.loc[0, "Salary"] * 0.10
df1

,Employee id,Name,Age,Salary,City,Bonus,Total Compensation
0,1,Sahil,25,55000,New York,5500.0,55000.0
1,2,john,30,60000,Los Angeles,6000.0,66000.0
2,3,michael,35,70000,Chicago,7000.0,77000.0
3,4,susan,40,80000,Houston,8000.0,88000.0
4,5,lisa,45,90000,Phoenix,9000.0,99000.0
5,6,david,50,100000,Philadelphia,10000.0,110000.0
6,7,jessica,55,110000,San Antonio,11000.0,121000.0
7,8,robert,60,120000,San Diego,12000.0,132000.0
8,9,linda,65,130000,Dallas,13000.0,143000.0
9,10,james,70,140000,San Jose,14000.0,154000.0

In [28]:
df1.loc[0, "Total Compensation"] = df1.lobc[0, "Salary"] + df1.loc[0, "Bonus"]
df1

AttributeError: 'DataFrame' object has no attribute 'lobc'

In [ ]:
df1.to_csv("employee_data.csv", index=False)

In [ ]:
import pandas as pd

data = {
    "Months" : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
}
df = pd.DataFrame(data)
df

df["Short Month"] = df["Months"].str[:3]

# alternative way to create short month column

In [ ]:
data1 = {
    "Months" : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
}

df1 = pd.DataFrame(data1)
# print(df1)
def short_month(month):
    return month[:3]

df1["Short Month"] = df1["Months"].map(short_month)
df1

       Months Short Month
0     January         Jan
1    February         Feb
2       March         Mar
3       April         Apr
4         May         May
5        June         Jun
6        July         Jul
7      August         Aug
8   September         Sep
9     October         Oct
10   November         Nov
11   December         Dec

In [ ]:
ESD_data = pd.read_excel("ESD.xlsx")
ESD_data.head()

# ESD_data.isnull().sum()
gp = ESD_data.groupby("Department").agg(
    {
        "Gender" : "count",
    }
)
gp

                 Gender
Department
Accounting           96
Engineering         158
Finance             120
Human Resources     125
IT                  241
Marketing           120
Sales               140

In [ ]:
gp = ESD_data.groupby(["Department", "Gender"]).agg(
    { 
        "EEID" : "count",
    }
)
gp

                        EEID
Department      Gender
Accounting      Female    53
                Male      43
Engineering     Female    80
                Male      78
Finance         Female    69
                Male      51
Human Resources Female    64
                Male      61
IT              Female   119
                Male     122
Marketing       Female    57
                Male      63
Sales           Female    76
                Male      64

In [ ]:
print("Git Uploaded")

Git Uploaded