In [1]:
import pandas as pd
import pyodbc
from warnings import filterwarnings

In [2]:
# import pandas as pd

# # 1. Create a list of your 5 CSV file paths
# files = ['../begin_inventory.csv', '../purchase_prices.csv', '../purchases.csv', '../sales.csv', '../end_inventory.csv']

# # 2. Use a for loop to read each and print the row count
# for file in files:
#     data = pd.read_csv(file)
#     print(f"{file}\n")
#     print(data.head(5))

In [3]:
# df= pd.read_csv('../sales.csv')
# df.info()

In [4]:
conn = pyodbc.connect('DRIVER={SQL Server};SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;DATABASE=My_Project;Trusted_Connection=yes;')
if conn:
    print("Connection successful!")

Connection successful!

<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\1838932837.py:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  conn = pyodbc.connect('DRIVER={SQL Server};SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;DATABASE=My_Project;Trusted_Connection=yes;')

In [5]:
purchases = pd.read_sql_query('SELECT * FROM purchases where VendorNumber = 4466', conn)
purchases

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\76446512.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  purchases = pd.read_sql_query('SELECT * FROM purchases where VendorNumber = 4466', conn)

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.400002,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.049999,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.099998,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.459999,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.459999,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.459999,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.750000,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.049999,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.459999,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.750000,1

In [6]:
purchase_price = pd.read_sql_query('SELECT * FROM purchase_prices where VendorNumber = 4466', conn)
purchase_price

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\2685471258.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  purchase_price = pd.read_sql_query('SELECT * FROM purchase_prices where VendorNumber = 4466', conn)

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

vendor_invoice = pd.read_sql_query('SELECT * FROM vendor_invoice where VendorNumber = 4466', conn)
vendor_invoice

In [7]:
sales = pd.read_sql_query("select * from sales where VendorNo = 4466", conn)
sales

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\1173318207.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales = pd.read_sql_query("select * from sales where VendorNo = 4466", conn)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [8]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity       Dollars
Brand PurchasePrice
3140  11.19              4640  51921.599669
5215  9.41               4923  46325.429382
5255  9.35               6215  58110.248949

In [9]:
# purchase_price
vendor_invoice = pd.read_sql_query("select * from vendor_invoice", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\285574814.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vendor_invoice = pd.read_sql_query("select * from vendor_invoice", conn)

In [10]:
vendor_invoice['PONumber'].nunique()

5543

In [11]:
vendor_invoice.shape

(5543, 10)

In [12]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [13]:
sales.groupby('Brand')[["SalesDollars", "SalesPrice", "SalesQuantity"]].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

### Calculating freight cost fro each vendors using sql query

In [14]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [15]:
freight_summary = pd.read_sql_query("select VendorNumber, SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber order by VendorNumber asc", conn)
freight_summary

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\401002919.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  freight_summary = pd.read_sql_query("select VendorNumber, SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber order by VendorNumber asc", conn)

     VendorNumber  FreightCost
0               2    27.080001
1              54     0.480000
2              60   367.520002
3             105    62.389999
4             200     6.190000
..            ...          ...
121         98450   856.019997
122         99166   130.090001
123        172662   178.340000
124        173357   202.500001
125        201359     0.090000

[126 rows x 2 columns]

In [16]:
pd.read_sql_query( """
SELECT 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,           
    pp.Volume,                 
    pp.Price AS ActualPrice,   
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp ON p.Brand = pp.Brand
WHERE p.PurchasePrice > 0
GROUP BY 
    p.VendorNumber, 
    p.VendorName, 
    p.Brand, 
    p.PurchasePrice,     
    pp.Volume,                 
    pp.Price                   
ORDER BY TotalPurchaseDollars;
""", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\148718205.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query( """

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.710000,50.0,0.990000,1,7.100000e-01
1,3960,DIAGEO NORTH AMERICA INC,6127,1.470000,200.0,1.990000,1,1.470000e+00
2,3924,HEAVEN HILL DISTILLERIES,9123,0.740000,50.0,0.990000,2,1.480000e+00
3,8004,SAZERAC CO INC,5683,0.390000,50.0,0.490000,6,2.340000e+00
4,9815,WINE GROUP INC,8527,1.320000,750.0,4.990000,2,2.640000e+00
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.889999,1750.0,29.990000,138109,3.023206e+06
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.170000,1750.0,22.990000,201682,3.261198e+06
10689,17035,PERNOD RICARD USA,8068,18.240000,1750.0,24.990000,187407,3.418304e+06
10690,4425,MARTIGNETTI COMPANIES,3405,23.190001,1750.0,28.990000,164038,3.804041e+06
10691,1128,BROWN-FORMAN CORP,1233,26.270000,1750.0,36.990002,145080,3.811252e+06

In [17]:
pd.read_sql_query("""SELECT
                  VendorNo,
                  Brand,
                  SUM(SalesDollars) AS TotalSalesDollars,
                  SUM(SalesPrice) AS TotalSalesPrice,
                  SUM(SalesQuantity) AS TotalSalesQuantity,
                  SUM(ExciseTax) AS TotalExciseTax
                  FROM sales
                  Group By VendorNo,Brand
                  Order by TotalSalesDollars
                  """,conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\904892026.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("""SELECT

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,1.98,0.99,2,0.10
3,10050,3623,1.98,1.98,2,0.10
4,3924,9123,1.98,0.99,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,135838,249587.83
11268,3960,4261,4475972.88,420050.01,200412,368242.80
11269,17035,8068,4538120.60,461140.15,187140,343854.07
11270,4425,3405,4819073.49,561512.37,160247,294438.66
11271,1128,1233,5101919.51,672819.31,142049,260999.20

In [18]:
# import time 
# start = time.time()
# final_table = pd.read_sql_query("""SELECT 
#                                 pp.VendorNumber,
#                                 pp.Brand,
#                                 pp.Price AS ActualPrice,
#                                 pp.PurchasePrice,
#                                 SUM(s.SalesDollars) AS TotalSalesDollars,
#                                 SUM(s.SalesPrice) AS TotalSalesPrice,
#                                 SUM(SalesQuantity) AS TotalSalesQuantity,
#                                 SUM(ExciseTax) AS TotalExciseTax,
#                                 SUM(vi.Quantity) AS TotalPurchaseQuantity,
#                                 SUM(vi.Dollars) AS TotalPurchaseDollars,
#                                 SUM(vi.Freight) AS TotalFreightCost
#                                 from purchase_prices pp
#                                 JOIN sales s
#                                 ON pp.VendorNumber = s.VendorNo
#                                 AND pp.Brand = s.Brand 
#                                 JOIN vendor_invoice vi
#                                 ON pp.VendorNumber = vi.VendorNumber
#                                 GROUP BY pp.VendorNumber, pp.Brand, pp.Price, pp.PurchasePrice
#                                 """,conn)
# end = time.time()

vendor_sales_summary =  pd.read_sql_query("""
    with FreightSummary as (
	select VendorNumber,
	SUM(Freight) as FreightCost
	from vendor_invoice
	group by VendorNumber
),
PurchaseSummary as (
	select 
	p.VendorNumber,
	p.VendorName,
	p.Brand,
	p.Description,
	p.PurchasePrice,
	pp.Price as ActualPrice,
	pp.Volume,
	SUM(p.Quantity) as TotalPurchaseQuaantity,
	SUM(p.Dollars) as TotalPurchaseDollars 
	from purchases p
	join purchase_prices pp
	on p.Brand = pp.Brand
	where p.PurchasePrice > 0 
	group by p.VendorName, p.VendorNumber, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume
),
SalesSummary as (
	select 
	VendorNo,
	Brand,
	SUM(SalesQuantity) as TotalSalesQuantity,
	SUM(SalesDollars) as TotalSalesDollars,
	SUM(SalesPrice) as TotalSalesPrice,
	SUM(ExciseTax) as TotalExciseTax
	from sales
	group by VendorNo, Brand
)

select 
	ps.VendorNumber,
	ps.VendorName,
	ps.Brand,
	ps.Description,
	ps.PurchasePrice,
	ps.ActualPrice,
	ps.Volume,
	ps.TotalPurchaseQuaantity,
	ps.TotalPurchaseDollars,
	ss.TotalSalesQuantity,
	ss.TotalSalesDollars,
	ss.TotalSalesPrice,
	ss.TotalExciseTax,
	fs.FreightCost
	from PurchaseSummary ps
left join SalesSummary ss
    on ps.VendorNumber = ss.VendorNo
    and ps.Brand = ss.Brand
left join FreightSummary fs
    on ps.VendorNumber = fs.VendorNumber
order by ps.TotalPurchaseDollars DESC    
""", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_7852\1332335168.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vendor_sales_summary =  pd.read_sql_query("""

In [19]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuaantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.270000,36.990002,1750.0,145080,3.811252e+06,142049.0,5101919.51,672819.31,260999.20,68601.680141
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.190001,28.990000,1750.0,164038,3.804041e+06,160247.0,4819073.49,561512.37,294438.66,144929.240166
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.240000,24.990000,1750.0,187407,3.418304e+06,187140.0,4538120.60,461140.15,343854.07,123780.220203
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.170000,22.990000,1750.0,201682,3.261198e+06,200412.0,4475972.88,420050.01,368242.80,257032.069523
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.889999,29.990000,1750.0,138109,3.023206e+06,135838.0,4223107.62,545778.28,249587.83,257032.069523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.320000,4.990000,750.0,2,2.640000e+00,5.0,15.95,10.96,0.55,27100.410036
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.390000,0.490000,50.0,6,2.340000e+00,134.0,65.66,1.47,7.04,50293.619843
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.740000,0.990000,50.0,2,1.480000e+00,2.0,1.98,0.99,0.10,14069.870026
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.470000,1.990000,200.0,1,1.470000e+00,72.0,143.28,77.61,15.12,257032.069523
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.710000,0.990000,50.0,1,7.100000e-01,86.0,85.14,33.66,4.46,38994.780066

In [20]:
vendor_sales_summary.dtypes

VendorNumber                int64
VendorName                    str
Brand                       int64
Description                   str
PurchasePrice             float64
ActualPrice               float64
Volume                    float64
TotalPurchaseQuaantity      int64
TotalPurchaseDollars      float64
TotalSalesQuantity        float64
TotalSalesDollars         float64
TotalSalesPrice           float64
TotalExciseTax            float64
FreightCost               float64
dtype: object

In [37]:
vendor_sales_summary.isnull().sum()

VendorNumber              0
VendorName                0
Brand                     0
Description               0
PurchasePrice             0
ActualPrice               0
Volume                    0
TotalPurchaseQuaantity    0
TotalPurchaseDollars      0
TotalSalesQuantity        0
TotalSalesDollars         0
TotalSalesPrice           0
TotalExciseTax            0
FreightCost               0
GrossProfit               0
dtype: int64

In [35]:
vendor_sales_summary['VendorName'].unique

<bound method Series.unique of 0               BROWN-FORMAN CORP
1           MARTIGNETTI COMPANIES
2               PERNOD RICARD USA
3        DIAGEO NORTH AMERICA INC
4        DIAGEO NORTH AMERICA INC
                   ...
10687              WINE GROUP INC
10688              SAZERAC CO INC
10689    HEAVEN HILL DISTILLERIES
10690    DIAGEO NORTH AMERICA INC
10691        PROXIMO SPIRITS INC.
Name: VendorName, Length: 10692, dtype: str>

In [25]:
vendor_sales_summary['Description'].unique()

<StringArray>
[    'Jack Daniels No 7 Black',       'Tito's Handmade Vodka',
            'Absolut 80 Proof',      'Capt Morgan Spiced Rum',
             'Ketel One Vodka',            'Grey Goose Vodka',
       'Jameson Irish Whiskey',           'Smirnoff Traveler',
                   'Tanqueray',                    'Jim Beam',
 ...
         'Riunite Sweet White',         'Firefly Ridge Chard',
           'Debauchery Pnt Nr', 'Terruzzi & Puthod Vernaccia',
  'Santa Rita Organic Svgn Bl',    'Aresti Pnt Nr Curico Vly',
   'Smirnoff Light Strawberry',           'Crown Royal Apple',
 'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita']
Length: 9651, dtype: str

In [26]:
vendor_sales_summary.fillna(0, inplace=True)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuaantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.270000,36.990002,1750.0,145080,3.811252e+06,142049.0,5101919.51,672819.31,260999.20,68601.680141
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.190001,28.990000,1750.0,164038,3.804041e+06,160247.0,4819073.49,561512.37,294438.66,144929.240166
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.240000,24.990000,1750.0,187407,3.418304e+06,187140.0,4538120.60,461140.15,343854.07,123780.220203
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.170000,22.990000,1750.0,201682,3.261198e+06,200412.0,4475972.88,420050.01,368242.80,257032.069523
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.889999,29.990000,1750.0,138109,3.023206e+06,135838.0,4223107.62,545778.28,249587.83,257032.069523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.320000,4.990000,750.0,2,2.640000e+00,5.0,15.95,10.96,0.55,27100.410036
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.390000,0.490000,50.0,6,2.340000e+00,134.0,65.66,1.47,7.04,50293.619843
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.740000,0.990000,50.0,2,1.480000e+00,2.0,1.98,0.99,0.10,14069.870026
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.470000,1.990000,200.0,1,1.470000e+00,72.0,143.28,77.61,15.12,257032.069523
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.710000,0.990000,50.0,1,7.100000e-01,86.0,85.14,33.66,4.46,38994.780066

In [34]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [36]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [39]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit']/ vendor_sales_summary['TotalSalesDollars']*100)

In [45]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [40]:
vendor_sales_summary['SalestoPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [46]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,SalestoPurchaseRatio,StockTurnover
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.270000,36.990002,1750.0,145080,3.811252e+06,142049.0,5101919.51,672819.31,260999.20,68601.680141,1.290668e+06,25.297693,1.338647,0.979108
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.190001,28.990000,1750.0,164038,3.804041e+06,160247.0,4819073.49,561512.37,294438.66,144929.240166,1.015032e+06,21.062809,1.266830,0.976890
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.240000,24.990000,1750.0,187407,3.418304e+06,187140.0,4538120.60,461140.15,343854.07,123780.220203,1.119817e+06,24.675786,1.327594,0.998575
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.170000,22.990000,1750.0,201682,3.261198e+06,200412.0,4475972.88,420050.01,368242.80,257032.069523,1.214775e+06,27.139908,1.372493,0.993703
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.889999,29.990000,1750.0,138109,3.023206e+06,135838.0,4223107.62,545778.28,249587.83,257032.069523,1.199902e+06,28.412765,1.396897,0.983556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.320000,4.990000,750.0,2,2.640000e+00,5.0,15.95,10.96,0.55,27100.410036,1.331000e+01,83.448275,6.041666,2.500000
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.390000,0.490000,50.0,6,2.340000e+00,134.0,65.66,1.47,7.04,50293.619843,6.332000e+01,96.436187,28.059830,22.333333
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.740000,0.990000,50.0,2,1.480000e+00,2.0,1.98,0.99,0.10,14069.870026,5.000000e-01,25.252524,1.337838,1.000000
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.470000,1.990000,200.0,1,1.470000e+00,72.0,143.28,77.61,15.12,257032.069523,1.418100e+02,98.974037,97.469386,72.000000
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.710000,0.990000,50.0,1,7.100000e-01,86.0,85.14,33.66,4.46,38994.780066,8.443000e+01,99.166079,119.915497,86.000000

In [53]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

# 1. Create the engine (This is what Pandas needs to recognize SQL Server)
quoted_conn = urllib.parse.quote_plus(
    r'DRIVER={ODBC Driver 17 for SQL Server};'
    r'SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;' # Or your server name
    r'DATABASE=My_Project;'
    r'Trusted_Connection=yes;'
)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={quoted_conn}")

# 2. Use the 'engine' variable in to_sql
vendor_sales_summary.to_sql(
    name='Final_Summary_Table', 
    con=engine,               # Use 'engine', NOT 'conn'
    if_exists='replace', 
    index=False, 
    chunksize=5000
)

print("Uploaded successfully to SSMS!")

DatabaseError: Execution failed on sql 'INSERT INTO "Final_Summary_Table" ("VendorNumber", "VendorName", "Brand", "Description", "PurchasePrice", "ActualPrice", "Volume", "TotalPurchaseQuantity", "TotalPurchaseDollars", "TotalSalesQuantity", "TotalSalesDollars", "TotalSalesPrice", "TotalExciseTax", "FreightCost", "GrossProfit", "ProfitMargin", "SalestoPurchaseRatio", "StockTurnover") VALUES (:VendorNumber, :VendorName, :Brand, :Description, :PurchasePrice, :ActualPrice, :Volume, :TotalPurchaseQuantity, :TotalPurchaseDollars, :TotalSalesQuantity, :TotalSalesDollars, :TotalSalesPrice, :TotalExciseTax, :FreightCost, :GrossProfit, :ProfitMargin, :SalestoPurchaseRatio, :StockTurnover)': (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 379 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[SQL: INSERT INTO [Final_Summary_Table] ([VendorNumber], [VendorName], [Brand], [Description], [PurchasePrice], [ActualPrice], [Volume], [TotalPurchaseQuantity], [TotalPurchaseDollars], [TotalSalesQuantity], [TotalSalesDollars], [TotalSalesPrice], [TotalEx ... 6498 characters truncated ... ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (17035, 'PERNOD RICARD USA', 8780, 'Sandeman Fine Rich Madeira', 10.130000114440918, 16.989999771118164, 750.0, 2400, 24311.99956226349, 2407.0, 38503.93, 29785.37, 266.05, 123780.22020339966, 14191.930437736512, 36.858394552806715, 1.583741802124943, 1.0029166666666667, 1392, 'CONSTELLATION BRANDS INC', 21326, 'Kim Crawford Svgn Bl Sptfire', 16.229999542236328, 26.989999771118164, 750.0, 1497, 24296.30952835083, 1331.0, 35574.69, 21309.06, 147.79, 79528.99032592773, 11278.380471649172, 31.703383702427683, 1.4642013824564046, 0.8891115564462257, 1392, 'CONSTELLATION BRANDS INC', 32968, 'Alice White Chard Ausl', 6.800000190734863, 9.989999771118164, 1500.0, 3571, 24282.799648284912, 3943.0, 43800.57, 22057.13, 882.08, 79528.99032592773 ... 1988 parameters truncated ... 7.579999923706055, 10.989999771118164, 750.0, 2967, 22489.859828948975, 2942.0, 29533.58, 12794.26, 328.08, 28720.519941329956, 7043.720171051027, 23.849869101717523, 1.3131953789229198, 0.9915739804516347, 11567, 'CAMPARI AMERICA', 4876, 'Skyy Infusion Tropical Mango', 11.930000305175781, 15.989999771118164, 750.0, 1885, 22488.050415039062, 1490.0, 16643.1, 12782.7, 1174.43, 20964.810007333755, -5844.950415039064, -35.11936126706602, 0.740086387785301, 0.7904509283819628, 2000, 'SOUTHERN WINE & SPIRITS NE', 28681, 'F Coppola Rosso Bianco Rosso', 5.949999809265137, 8.989999771118164, 750.0, 3778, 22479.100289344788, 3913.0, 39586.87, 22031.37, 434.92, 19016.589984714985, 17107.769710655215, 43.21576752760502, 1.761052243659609, 1.0357331921651667)]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [57]:
# 1. Force infinities to become NaNs
vendor_sales_summary = vendor_sales_summary.replace([np.inf, -np.inf], np.nan)

# 2. Convert NaNs to None so SQL Server accepts them as NULL
vendor_sales_summary = vendor_sales_summary.where(pd.notnull(vendor_sales_summary), None)

In [63]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity         0
TotalSalesDollars          0
TotalSalesPrice            0
TotalExciseTax             0
FreightCost                0
GrossProfit                0
ProfitMargin             178
SalestoPurchaseRatio       0
StockTurnover              0
dtype: int64

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,SalestoPurchaseRatio,StockTurnover
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.270000,36.990002,1750.0,145080,3.811252e+06,142049.0,5101919.51,672819.31,260999.20,68601.680141,1.290668e+06,25.297693,1.338647,0.979108
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.190001,28.990000,1750.0,164038,3.804041e+06,160247.0,4819073.49,561512.37,294438.66,144929.240166,1.015032e+06,21.062809,1.266830,0.976890
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.240000,24.990000,1750.0,187407,3.418304e+06,187140.0,4538120.60,461140.15,343854.07,123780.220203,1.119817e+06,24.675786,1.327594,0.998575
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.170000,22.990000,1750.0,201682,3.261198e+06,200412.0,4475972.88,420050.01,368242.80,257032.069523,1.214775e+06,27.139908,1.372493,0.993703
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.889999,29.990000,1750.0,138109,3.023206e+06,135838.0,4223107.62,545778.28,249587.83,257032.069523,1.199902e+06,28.412765,1.396897,0.983556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.320000,4.990000,750.0,2,2.640000e+00,5.0,15.95,10.96,0.55,27100.410036,1.331000e+01,83.448275,6.041666,2.500000
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.390000,0.490000,50.0,6,2.340000e+00,134.0,65.66,1.47,7.04,50293.619843,6.332000e+01,96.436187,28.059830,22.333333
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.740000,0.990000,50.0,2,1.480000e+00,2.0,1.98,0.99,0.10,14069.870026,5.000000e-01,25.252524,1.337838,1.000000
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.470000,1.990000,200.0,1,1.470000e+00,72.0,143.28,77.61,15.12,257032.069523,1.418100e+02,98.974037,97.469386,72.000000
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.710000,0.990000,50.0,1,7.100000e-01,86.0,85.14,33.66,4.46,38994.780066,8.443000e+01,99.166079,119.915497,86.000000

In [64]:
import numpy as np

# 1. Convert any hidden infinities (inf or -inf) into NaN
vendor_sales_summary = vendor_sales_summary.replace([np.inf, -np.inf], np.nan)

# 2. Fill all those NaN values with 0
vendor_sales_summary = vendor_sales_summary.fillna(0)

# 3. Use the 'engine' variable in to_sql
vendor_sales_summary.to_sql(
    name='Final_Summary_Table', 
    con=engine,               
    if_exists='replace', 
    index=False, 
    chunksize=5000
)

print("Uploaded successfully to SSMS!")

Uploaded successfully to SSMS!