In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('car_price.csv')

In [3]:
data.head(5)

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,Mahindra Jeep CL 500 MDI,2.60 Lakh,"1,00,000 kms",Diesel,Manual,1st Owner,1995,1199 cc,6 Seats
1,Maruti Zen VXI,1.10 Lakh,"90,000 kms",Petrol,Manual,3rd Owner,1998,993 cc,5 Seats
2,Maruti Zen LX,"60,000","1,00,000 kms",Petrol,Manual,2nd Owner,1998,1591 cc,5 Seats
3,Maruti 800 Std,"35,000","80,000 kms",Petrol,Manual,2nd Owner,1999,1997 cc,5 Seats
4,Maruti 800 Std,"45,000","50,000 kms",Petrol,Manual,4th Owner,2000,1197 cc,7 Seats

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5512 entries, 0 to 5511
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             5512 non-null   str
 1   car_prices_in_rupee  5512 non-null   str
 2   kms_driven           5512 non-null   str
 3   fuel_type            5512 non-null   str
 4   transmission         5512 non-null   str
 5   ownership            5512 non-null   str
 6   manufacture          5512 non-null   int64
 7   engine               5512 non-null   str
 8   Seats                5512 non-null   str
dtypes: int64(1), str(8)
memory usage: 387.7 KB

In [5]:
data.shape

(5512, 9)

In [8]:
data.isnull().sum().sum()/data.shape[0] * 100

np.float64(0.0)

# Car Name

In [9]:
data['car_name']

0                    Mahindra Jeep CL 500 MDI
1                              Maruti Zen VXI
2                               Maruti Zen LX
3                              Maruti 800 Std
4                              Maruti 800 Std
                        ...
5507               Volvo XC60 B5 Inscripition
5508           Hyundai Venue SX Opt Turbo iMT
5509                 Hyundai Venue SX Opt iMT
5510             Mercedes-Benz C-Class C 220d
5511    Mercedes-Benz A-Class Limousine A 200
Name: car_name, Length: 5512, dtype: str

In [11]:
data['company'] = data['car_name'].str.split().str[0]

In [13]:
data

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,company
0,Mahindra Jeep CL 500 MDI,2.60 Lakh,"1,00,000 kms",Diesel,Manual,1st Owner,1995,1199 cc,6 Seats,Mahindra
1,Maruti Zen VXI,1.10 Lakh,"90,000 kms",Petrol,Manual,3rd Owner,1998,993 cc,5 Seats,Maruti
2,Maruti Zen LX,"60,000","1,00,000 kms",Petrol,Manual,2nd Owner,1998,1591 cc,5 Seats,Maruti
3,Maruti 800 Std,"35,000","80,000 kms",Petrol,Manual,2nd Owner,1999,1997 cc,5 Seats,Maruti
4,Maruti 800 Std,"45,000","50,000 kms",Petrol,Manual,4th Owner,2000,1197 cc,7 Seats,Maruti
...,...,...,...,...,...,...,...,...,...,...
5507,Volvo XC60 B5 Inscripition,68.50 Lakh,"7,000 kms",Petrol,Automatic,1st Owner,2022,1995 cc,5 Seats,Volvo
5508,Hyundai Venue SX Opt Turbo iMT,10.25 Lakh,"15,000 kms",Petrol,Manual,1st Owner,2022,1396 cc,5 Seats,Hyundai
5509,Hyundai Venue SX Opt iMT,9.50 Lakh,"15,000 kms",Petrol,Manual,1st Owner,2022,936 cc,7 Seats,Hyundai
5510,Mercedes-Benz C-Class C 220d,53 Lakh,"9,000 kms",Diesel,Automatic,0th Owner,2022,1462 cc,5 Seats,Mercedes-Benz
5511,Mercedes-Benz A-Class Limousine A 200,42 Lakh,"3,000 kms",Petrol,Automatic,1st Owner,2022,1999 cc,5 Seats,Mercedes-Benz

In [14]:
def car_name(x):
    return x[x.index(" ")+1:]

In [15]:
data["car_name"] = data["car_name"].apply(car_name)

In [18]:
data[["company","car_name"]]

            company                 car_name
0          Mahindra          Jeep CL 500 MDI
1            Maruti                  Zen VXI
2            Maruti                   Zen LX
3            Maruti                  800 Std
4            Maruti                  800 Std
...             ...                      ...
5507          Volvo     XC60 B5 Inscripition
5508        Hyundai   Venue SX Opt Turbo iMT
5509        Hyundai         Venue SX Opt iMT
5510  Mercedes-Benz           C-Class C 220d
5511  Mercedes-Benz  A-Class Limousine A 200

[5512 rows x 2 columns]

# car_price_rupees

35,000 , 28.02 lakh , 1.02 crore

In [19]:
data["car_prices_in_rupee"]

0        2.60 Lakh
1        1.10 Lakh
2           60,000
3           35,000
4           45,000
           ...
5507    68.50 Lakh
5508    10.25 Lakh
5509     9.50 Lakh
5510       53 Lakh
5511       42 Lakh
Name: car_prices_in_rupee, Length: 5512, dtype: str

In [22]:
data["car_prices_in_rupee"] = data["car_prices_in_rupee"].str.replace(",", "")

In [ ]:
data["car_prices_in_rupee"]

In [23]:
def clean_price(x):
    x = str(x).lower().strip()
    x = x.replace(',', '')  # remove commas
    
    if 'lakh' in x:
        return float(x.replace('lakh', '').strip()) * 100000
    elif 'crore' in x:
        return float(x.replace('crore', '').strip()) * 10000000
    else:
        return float(x)

In [26]:
data['car_prices_in_rupee'] = data['car_prices_in_rupee'].apply(clean_price)

In [36]:
data['car_prices_in_rupee']

0        260000.0
1        110000.0
2         60000.0
3         35000.0
4         45000.0
          ...
5507    6850000.0
5508    1025000.0
5509     950000.0
5510    5300000.0
5511    4200000.0
Name: car_prices_in_rupee, Length: 5512, dtype: float64

# Kms Drive

In [32]:
data["kms_driven"] = data["kms_driven"].str.replace(",","")
data['kms_driven'] = data["kms_driven"].str.replace(" kms","")

In [35]:
data["kms_driven"] = data["kms_driven"].astype("int64")

In [37]:
data["kms_driven"]

0       100000
1        90000
2       100000
3        80000
4        50000
         ...
5507      7000
5508     15000
5509     15000
5510      9000
5511      3000
Name: kms_driven, Length: 5512, dtype: int64

# Engine

In [39]:
data["engine"] = data["engine"].str.replace(" cc", "")
data["engine"] = data["engine"].astype("int64")

In [40]:
data["engine"]

0       1199
1        993
2       1591
3       1997
4       1197
        ...
5507    1995
5508    1396
5509     936
5510    1462
5511    1999
Name: engine, Length: 5512, dtype: int64

# seats

In [41]:
data["Seats"] = data["Seats"].str.replace(" Seats", "")
data["Seats"] = data["Seats"].astype("int64")

In [42]:
data["Seats"]

0       6
1       5
2       5
3       5
4       7
       ..
5507    5
5508    5
5509    7
5510    5
5511    5
Name: Seats, Length: 5512, dtype: int64

# Manufacture Date