# Import pyodbc

In [2]:
import pyodbc
import pandas as pd
import numpy as np
from warnings import filterwarnings

# Make Connection First

In [3]:
conn = pyodbc.connect('DRIVER={SQL Server};SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;DATABASE=Data_Analyst;Trusted_Connection=yes;')
if conn:
    print("Connection successful!")

Connection successful!

<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\SAHIL\AppData\Local\Temp\ipykernel_15136\3789079924.py:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  conn = pyodbc.connect('DRIVER={SQL Server};SERVER=LAPTOP-JF5CSB68\SQLEXPRESS;DATABASE=Data_Analyst;Trusted_Connection=yes;')

# Get Data From The SQL Using Query

In [4]:
# filterwarnings("ignore", category=UserWarning, message=".*pandas only supports SQLAlchemy connectable.*")
df = pd.read_sql_query('SELECT * FROM employees', conn)
df

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_15136\2514620372.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('SELECT * FROM employees', conn)

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.800781,2024-05-23,42
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.320312,2021-10-02,46
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.308594,2020-04-30,50
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.738281,2021-04-04,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.562500,2020-10-06,51
...,...,...,...,...,...,...,...,...
995,996,Brandi,Cowan,qsimmons@gmail.com,Finance,97102.570312,2024-11-07,41
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.730469,2023-03-11,37
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,Finance,72886.031250,2024-07-25,32
998,999,April,Howard,crystalcohen@smith.com,Operations,32177.630859,2022-04-06,29
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.820312,2020-04-03,38

# Select 'email' column where it ends with '@gmail.com'

In [5]:
# Select 'email' column where it ends with '@gmail.com'
gmail_emails = df.loc[df['email'].str.endswith('gmail.com', na=False), 'email']
gmail_emails

0        alexandra29@gmail.com
5           parksamy@gmail.com
14       cherylbanks@gmail.com
20      smithgarrett@gmail.com
26      isabellahall@gmail.com
                ...
990    jamesjeanette@gmail.com
991    gutierrezerin@gmail.com
994      christine82@gmail.com
995         qsimmons@gmail.com
996      curtisruben@gmail.com
Name: email, Length: 173, dtype: str

# df by Department (ascending) and Age (descending)

In [6]:
sorted_df =df.sort_values(by=['department', 'age'], ascending=[True, False])
sorted_df

,employee_id,first_name,last_name,email,department,salary,joining_date,age
181,182,Samantha,Adams,bsmith@gmail.com,Finance,52614.660156,2024-06-09,60
272,273,Christina,Rodriguez,ruizdonna@gmail.com,Finance,57127.820312,2022-04-16,60
283,284,Michele,Ellis,diana70@yahoo.com,Finance,41902.628906,2021-04-30,60
493,494,Gregory,Mason,howardandrew@yahoo.com,Finance,31196.330078,2024-01-04,60
653,654,Jeremy,Fox,jamiepierce@hotmail.com,Finance,47327.578125,2021-03-10,60
...,...,...,...,...,...,...,...,...
405,406,Megan,Gomez,johnhurley@hotmail.com,Operations,91382.242188,2020-12-21,22
514,515,Christine,Alvarez,daniel88@gmail.com,Operations,65622.500000,2023-03-23,22
637,638,Valerie,Arnold,nelsoncameron@hotmail.com,Operations,43962.851562,2020-10-12,22
857,858,Heather,Ortiz,mshah@gmail.com,Operations,60848.710938,2020-01-16,22
897,898,Michelle,Jones,gary64@hotmail.com,Operations,91463.492188,2021-09-25,22

## The pandas equivalent of WHERE department IN ('IT', 'Marketing')

In [7]:
it_marketing_df = df[df['department'].isin(['IT', 'Marketing']) ]
it_marketing_df

,employee_id,first_name,last_name,email,department,salary,joining_date,age
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.320312,2021-10-02,46
6,7,Sabrina,Gonzalez,rwillis@mason-clark.biz,Marketing,88476.718750,2020-10-15,48
7,8,Jillian,Lewis,sreese@mclean-baker.net,Marketing,49895.550781,2021-06-08,33
10,11,Sara,Miller,tmoore@warren-lewis.org,Marketing,68588.453125,2020-07-21,26
12,13,Elizabeth,Johnson,ramirezbriana@hotmail.com,IT,83585.453125,2023-12-11,27
...,...,...,...,...,...,...,...,...
989,990,Frank,Miller,jennifer07@manning.com,IT,73566.742188,2020-11-19,51
990,991,Dillon,Maldonado,jamesjeanette@gmail.com,IT,31881.599609,2020-07-17,56
994,995,Mary,Wagner,christine82@gmail.com,Marketing,35956.070312,2023-12-15,45
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.730469,2023-03-11,37
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.820312,2020-04-03,38

## (The "NOT IN" version)

In [8]:
## The pandas equivalent of: 
# WHERE department NOT IN ('IT', 'Marketing') AND last_name NOT IN ('Wolf', 'Wong')
# filtered_df = df[
#     ~df['department'].isin(['IT', 'Marketing']) & 
#     ~df['last_name'].isin(['Wolf', 'Wong'])
# ]

it_marketing_df_Not = df[~df['department'].isin(['IT', 'Marketing']) ]
it_marketing_df_Not

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.800781,2024-05-23,42
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.308594,2020-04-30,50
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.738281,2021-04-04,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.562500,2020-10-06,51
5,6,Louis,Rivera,parksamy@gmail.com,Finance,30448.720703,2020-05-05,41
...,...,...,...,...,...,...,...,...
992,993,Richard,Bright,kimdebbie@hotmail.com,HR,39884.281250,2021-07-07,36
993,994,Daniel,White,michaelmorgan@rodriguez.org,Finance,34859.949219,2020-11-16,39
995,996,Brandi,Cowan,qsimmons@gmail.com,Finance,97102.570312,2024-11-07,41
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,Finance,72886.031250,2024-07-25,32
998,999,April,Howard,crystalcohen@smith.com,Operations,32177.630859,2022-04-06,29

# String Function

In [9]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']
result = df[['first_name', 'last_name', 'full_name']]
result

    first_name  last_name            full_name
0       Joshua      Ramos         Joshua Ramos
1    Christina      Clark      Christina Clark
2     Jonathon   Sullivan    Jonathon Sullivan
3      Clinton    Aguirre      Clinton Aguirre
4     Veronica      Weber       Veronica Weber
..         ...        ...                  ...
995     Brandi      Cowan         Brandi Cowan
996    Michael       Gray         Michael Gray
997  Cassandra  Rodriguez  Cassandra Rodriguez
998      April     Howard         April Howard
999   Benjamin     Palmer      Benjamin Palmer

[1000 rows x 3 columns]

### -Length Funtion Use

In [10]:
df['DigitCount'] = df['email'].str.len()
result = df[['email', 'DigitCount']]
result

                        email  DigitCount
0       alexandra29@gmail.com          21
1        littlekyle@yahoo.com          20
2      tannerivan@johnson.com          22
3       jamieortega@yahoo.com          21
4     trevinosteven@ramos.com          23
..                        ...         ...
995        qsimmons@gmail.com          18
996     curtisruben@gmail.com          21
997  brittneytran@dunlap.info          24
998    crystalcohen@smith.com          22
999  darylsnyder@williams.com          24

[1000 rows x 2 columns]

### -Upper Case Function use

In [11]:
df["UpperCaseFirstName"] = df['first_name'].str.upper()
# df["LowerCaseFirstName"] = df['first_name'].str.lower()
result = df[['first_name', 'UpperCaseFirstName']]
result

    first_name UpperCaseFirstName
0       Joshua             JOSHUA
1    Christina          CHRISTINA
2     Jonathon           JONATHON
3      Clinton            CLINTON
4     Veronica           VERONICA
..         ...                ...
995     Brandi             BRANDI
996    Michael            MICHAEL
997  Cassandra          CASSANDRA
998      April              APRIL
999   Benjamin           BENJAMIN

[1000 rows x 2 columns]

### - Creating Username using Slice funtion()

In [12]:
df['Username'] = df['first_name'].str[:4]
# df['LastNamePart'] = df['last_name'].str[-4:] # Example of extracting last 4 characters of last name
# df['MidName'] = df['first_name'].str[1:4] # Example of extracting characters from index 1 to 3 of first name
result = df[['first_name', 'Username']]
result

    first_name Username
0       Joshua     Josh
1    Christina     Chri
2     Jonathon     Jona
3      Clinton     Clin
4     Veronica     Vero
..         ...      ...
995     Brandi     Bran
996    Michael     Mich
997  Cassandra     Cass
998      April     Apri
999   Benjamin     Benj

[1000 rows x 2 columns]

In [13]:
df.describe()

       employee_id        salary          age   DigitCount
count  1000.000000   1000.000000  1000.000000  1000.000000
mean    500.500000  65112.385396    40.978000    21.931000
std     288.819436  19925.168172    11.398923     4.122528
min       1.000000  30102.759766    22.000000    14.000000
25%     250.750000  48008.141602    31.000000    19.000000
50%     500.500000  64585.640625    41.000000    22.000000
75%     750.250000  82785.630859    51.000000    24.000000
max    1000.000000  99969.687500    60.000000    37.000000

## Date & Time Function with SQL database

In [14]:
df_order = pd.read_sql_query('SELECT * FROM orders', conn)

df_order['orderDate'] = pd.to_datetime(df_order['orderDate'])
df_order['shippedDate'] = pd.to_datetime(df_order['shippedDate'])
df_order['DeliveryTime'] = (df_order['shippedDate'] - df_order['orderDate']).dt.days
result=df_order[['orderDate', 'shippedDate', 'DeliveryTime']]
result

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_15136\1585248535.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_order = pd.read_sql_query('SELECT * FROM orders', conn)

     orderDate shippedDate  DeliveryTime
0   2003-01-06  2003-01-10           4.0
1   2003-01-09  2003-01-11           2.0
2   2003-01-10  2003-01-14           4.0
3   2003-01-29  2003-02-02           4.0
4   2003-01-31  2003-02-01           1.0
..         ...         ...           ...
321 2005-05-29         NaT           NaN
322 2005-05-30         NaT           NaN
323 2005-05-30         NaT           NaN
324 2005-05-31         NaT           NaN
325 2005-05-31         NaT           NaN

[326 rows x 3 columns]

## Quick Cheat Sheet for Date Parts:
| Goal	  | SSMS (T-SQL) | 	Pandas |
|---|---|---|
| Day Name  | 	DATENAME(dw, date) | 	.dt.day_name() |
| Month Name| DATENAME(mm, date) | .dt.month_name() |
| Day of Month | 	DAY(date) | .dt.day |
| Year| 	YEAR(date)| 	.dt.year |

## Case Function

In [15]:
df_product = pd.read_sql_query("select * from products", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_15136\1687343932.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_product = pd.read_sql_query("select * from products", conn)

In [16]:
df_product['Production_details'] = np.where(
    df_product['quantityInStock'] < 1000,
    "Urgent need of Stock",
    "No Requirement"
)

result = df_product[['productName','quantityInStock','Production_details']]
result

,productName,quantityInStock,Production_details
0,1969 Harley Davidson Ultimate Chopper,7933,No Requirement
1,1952 Alpine Renault 1300,7305,No Requirement
2,1996 Moto Guzzi 1100i,6625,No Requirement
3,2003 Harley-Davidson Eagle Drag Bike,5582,No Requirement
4,1972 Alfa Romeo GTA,3252,No Requirement
...,...,...,...
105,The Titanic,1956,No Requirement
106,The Queen Mary,5088,No Requirement
107,American Airlines: MD-11S,8820,No Requirement
108,Boeing X-32A JSF,4857,No Requirement
109,Pont Yacht,414,Urgent need of Stock

# Group By Function

In [17]:
result = df.groupby('department')['employee_id'].count()
result

department
Finance       208
HR            205
IT            206
Marketing     190
Operations    191
Name: employee_id, dtype: int64

In [18]:
result = df.groupby('department')['salary'].sum().round(1)
result

department
Finance       13435202.1
HR            12827366.7
IT            14014682.0
Marketing     12479517.9
Operations    12355616.7
Name: salary, dtype: float64

In [19]:
result = df_product.groupby('productLine')['quantityInStock'].sum().sort_values(ascending=False)
result

productLine
Classic Cars        219183
Vintage Cars        124880
Motorcycles          69401
Planes               62287
Trucks and Buses     35851
Ships                26833
Trains               16696
Name: quantityInStock, dtype: int64

# Having Clause

In [20]:
# 1. Group and Sum (SELECT ... GROUP BY)
result = df_product.groupby('productLine', as_index=False).agg(Stock=('quantityInStock', 'sum'))

# 2. Filter the result (HAVING SUM > 20000)
result = result[result['Stock'] > 20000]

# 3. Sort the values (ORDER BY Stock DESC)
result = result.sort_values(by='Stock', ascending=False)

# Display result
print(result)

        productLine   Stock
0      Classic Cars  219183
6      Vintage Cars  124880
1       Motorcycles   69401
2            Planes   62287
5  Trucks and Buses   35851
3             Ships   26833

# Joins In Pandas using Sql File

In [21]:
df_Customers = pd.read_sql_query("Select * from Customers", conn)
df_Local_Orders = pd.read_sql_query("Select * from Local_Orders", conn)

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_15136\3005327143.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Customers = pd.read_sql_query("Select * from Customers", conn)
C:\Users\SAHIL\AppData\Local\Temp\ipykernel_15136\3005327143.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Local_Orders = pd.read_sql_query("Select * from Local_Orders", conn)

In [22]:
df_merge = pd.merge(df_Customers,df_Local_Orders, how='inner', on='CustomerID')
df_merge

    CustomerID CustomerName  Country  OrderID   Product  Quantity
0            1        Alice      USA      101    Laptop         2
1            1        Alice      USA      103  Keyboard        10
2            2          Bob       UK      102     Phone         5
3            3      Charlie      USA      104   Monitor         3
4            5          Eva  Germany      105     Mouse         4
5            6        Frank   Canada      106    Tablet         6
6            7        Grace   France      107    Camera         2
7            8       Hannah      USA      108   Headset         8
8            9         Ivan   Russia      109   Printer         1
9           10         Jack       UK      110   Scanner         5
10          11        Karen    India      111    Laptop         3
11          12          Leo  Germany      112     Phone         2
12          13         Mona      USA      113  Keyboard         7
13          14         Nina   France      114   Monitor         4
14          15        Oscar       UK      115     Mouse         9
15          16         Paul   Canada      116    Tablet         1
16          17        Quinn      USA      117    Camera         2
17          18         Rita    India      118   Headset         3
18          19          Sam  Germany      119   Printer         6
19          20         Tina       UK      120   Scanner         2

### Left Join

In [23]:
df_merge = pd.merge(df_Customers,df_Local_Orders, how='left', on='CustomerID')
df_merge

     CustomerID CustomerName  Country  OrderID   Product  Quantity
0             1        Alice      USA    101.0    Laptop       2.0
1             1        Alice      USA    103.0  Keyboard      10.0
2             2          Bob       UK    102.0     Phone       5.0
3             3      Charlie      USA    104.0   Monitor       3.0
4             4        David    India      NaN       NaN       NaN
..          ...          ...      ...      ...       ...       ...
96           96         Ryan      USA      NaN       NaN       NaN
97           97       Sophia   France      NaN       NaN       NaN
98           98          Tom       UK      NaN       NaN       NaN
99           99         Usha    India      NaN       NaN       NaN
100         100       Victor  Germany      NaN       NaN       NaN

[101 rows x 6 columns]

### Right Join

In [24]:
df_merge = pd.merge(df_Customers,df_Local_Orders, how='right', on='CustomerID')
df_merge

    CustomerID CustomerName  Country  OrderID   Product  Quantity
0            1        Alice      USA      101    Laptop         2
1            2          Bob       UK      102     Phone         5
2            1        Alice      USA      103  Keyboard        10
3            3      Charlie      USA      104   Monitor         3
4            5          Eva  Germany      105     Mouse         4
5            6        Frank   Canada      106    Tablet         6
6            7        Grace   France      107    Camera         2
7            8       Hannah      USA      108   Headset         8
8            9         Ivan   Russia      109   Printer         1
9           10         Jack       UK      110   Scanner         5
10          11        Karen    India      111    Laptop         3
11          12          Leo  Germany      112     Phone         2
12          13         Mona      USA      113  Keyboard         7
13          14         Nina   France      114   Monitor         4
14          15        Oscar       UK      115     Mouse         9
15          16         Paul   Canada      116    Tablet         1
16          17        Quinn      USA      117    Camera         2
17          18         Rita    India      118   Headset         3
18          19          Sam  Germany      119   Printer         6
19          20         Tina       UK      120   Scanner         2

### Cross Join

In [25]:
df_merge = pd.merge(df_Customers,df_Local_Orders, how='cross')
df_merge

,CustomerID_x,CustomerName,Country,OrderID,CustomerID_y,Product,Quantity
0,1,Alice,USA,101,1,Laptop,2
1,1,Alice,USA,102,2,Phone,5
2,1,Alice,USA,103,1,Keyboard,10
3,1,Alice,USA,104,3,Monitor,3
4,1,Alice,USA,105,5,Mouse,4
...,...,...,...,...,...,...,...
1995,100,Victor,Germany,116,16,Tablet,1
1996,100,Victor,Germany,117,17,Camera,2
1997,100,Victor,Germany,118,18,Headset,3
1998,100,Victor,Germany,119,19,Printer,6
1999,100,Victor,Germany,120,20,Scanner,2